### ISSUE TITLE
unidentified sign in UserRecord

### ISSUE THREAD

**Issue by bispinck** [Aachen-3A/PxlSkimmer#23]
When analysing file TT_13TeV_MCRUN2_74_V9_ext3-v1_PH_115.pxlio 
(dcap://grid-dcap-extern.physik.rwth-aachen.de/pnfs/physik.rwth-aachen.de/cms/store/user/padeken/PxlSkim/noTag/TT_13TeV_MCRUN2_74_V9_ext3-v1_PH/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MCRUN2_74_V9/150910_100547/0000/TT_13TeV_MCRUN2_74_V9_ext3-v1_PH_115.pxlio)

the program end with a segmentation violation and the warning: 

pxl::UserRecords Type  not handled in pxl::Variant I/O.

The same error is achieved when opening the pxlio file in vispa and jumping to the last event.

Although the program crashes with a segmentation violation the jobs is marked as good and returns an output histogram.

**Comment by padeken** [comment]
hmm the file seems to be corrupted the segfault is directy after calling readNextObject:

2015-10-19 17:06:40 [WARNING] pxl::UserRecords Type  not handled in pxl::Variant I/O.

Program received signal SIGSEGV, Segmentation fault.
0x00000000008aa0c9 in pxl::UserRecords::deserialize (this=0xc20c3c0, in=...) at Pxl/Pxl/src/UserRecord.cc:235
235             obj->deserialize(in);
(gdb) where
#0  0x00000000008aa0c9 in pxl::UserRecords::deserialize (this=0xc20c3c0, in=...) at Pxl/Pxl/src/UserRecord.cc:235
#1  0x0000000000815e20 in pxl::UserRecordHelper::deserialize (this=0xc20c3c0, in=...) at ./Pxl/Pxl/interface/pxl/core/UserRecord.hh:326
#2  0x00000000008737fa in pxl::Object::deserialize (this=0xc20c2d0, in=...) at Pxl/Pxl/src/Object.cc:27
#3  0x0000000000571e58 in pxl::ObjectManager::deserialize (this=0xc20c2d0, in=...) at ./Pxl/Pxl/interface/pxl/core/ObjectManager.hh:70
#4  0x0000000000850da8 in pxl::EventView::deserialize (this=0xc20c2d0, in=...) at ./Pxl/Pxl/interface/pxl/hep/EventView.hh:81
#5  0x000000000087dabe in pxl::ObjectOwner::deserialize (this=0xbf40230, in=...) at Pxl/Pxl/src/ObjectOwner.cc:295
#6  0x000000000084fcab in pxl::Event::deserialize (this=0xbf40210, in=...) at Pxl/Pxl/src/Event.cc:24
#7  0x000000000085e970 in pxl::InputHandler::readNextObject (this=0x7ffffffedd80) at Pxl/Pxl/src/InputHandler.cc:118
#8  0x00000000007e5c3d in main (argc=5, argv=0x7fffffff4a58) at Progs/music.cc:320

We should catch this automatically
